version: '3.8'

services:
  nats:
    image: nats:2
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["--js", "--store_dir=/data"]
    volumes:
      - nats-data:/data
    restart: unless-stopped

volumes:
  nats-data: