// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Feed struct {
	ID            int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	Url           string
	UserID        int64
	LastFetchedAt sql.NullTime
}

type FeedFilter struct {
	ID         int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	FilterText string
	Active     bool
	UserID     int64
	FeedID     int64
}

type FeedFollow struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int64
	FeedID    int64
}

type Post struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      int64
}

type PostRead struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int64
	PostID    int64
}

type Session struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Token     string
	ExpiresAt time.Time
	UserID    int64
}

type User struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Apikey    string
}
