// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (title, url, description, published_at, feed_id)
    VALUES (?, ?, ?, ?, ?)
    RETURNING id, created_at, updated_at, title, url, description, published_at, feed_id
`

type CreatePostParams struct {
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      int64
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Url,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Url,
		&i.Description,
		&i.PublishedAt,
		&i.FeedID,
	)
	return i, err
}

const getNewPostsForUser = `-- name: GetNewPostsForUser :many
SELECT p.id, p.created_at, p.updated_at, p.title, p.url, p.description, p.published_at, p.feed_id, f.name as feed_name FROM posts p
    INNER JOIN users u ON u.id = ff.user_id
    INNER JOIN feed_follows ff ON ff.feed_id=p.feed_id
    INNER JOIN feeds f ON f.id=p.feed_id
    LEFT JOIN post_reads pr ON pr.user_id=ff.user_id AND pr.post_id=p.id
    WHERE p.id IN (/*SLICE:newPostIDs*/?)
`

type GetNewPostsForUserRow struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      int64
	FeedName    string
}

func (q *Queries) GetNewPostsForUser(ctx context.Context, newpostids []int64) ([]GetNewPostsForUserRow, error) {
	query := getNewPostsForUser
	var queryParams []interface{}
	if len(newpostids) > 0 {
		for _, v := range newpostids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:newPostIDs*/?", strings.Repeat(",?", len(newpostids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:newPostIDs*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewPostsForUserRow
	for rows.Next() {
		var i GetNewPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadPostsForUser = `-- name: GetUnreadPostsForUser :many
SELECT p.id, p.created_at, p.updated_at, p.title, p.url, p.description, p.published_at, p.feed_id, f.name as feed_name FROM posts p
    INNER JOIN feed_follows ff ON ff.feed_id=p.feed_id
    INNER JOIN feeds f ON f.id=p.feed_id
    LEFT JOIN post_reads pr ON pr.user_id=ff.user_id AND pr.post_id=p.id
    WHERE ff.user_id=? AND pr.id IS NULL AND
        p.title LIKE ? AND
        (?=0 OR p.feed_id IN (/*SLICE:feedIDs*/?))
    ORDER BY p.published_at DESC LIMIT ?
`

type GetUnreadPostsForUserParams struct {
	UserID        int64
	SearchText    string
	FeedIDsLength interface{}
	FeedIDs       []int64
	Limit         int64
}

type GetUnreadPostsForUserRow struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Url         string
	Description sql.NullString
	PublishedAt sql.NullTime
	FeedID      int64
	FeedName    string
}

func (q *Queries) GetUnreadPostsForUser(ctx context.Context, arg GetUnreadPostsForUserParams) ([]GetUnreadPostsForUserRow, error) {
	query := getUnreadPostsForUser
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	queryParams = append(queryParams, arg.SearchText)
	queryParams = append(queryParams, arg.FeedIDsLength)
	if len(arg.FeedIDs) > 0 {
		for _, v := range arg.FeedIDs {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:feedIDs*/?", strings.Repeat(",?", len(arg.FeedIDs))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:feedIDs*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Limit)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnreadPostsForUserRow
	for rows.Next() {
		var i GetUnreadPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Url,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
